# ------------------------------------------------
#
# GitHUb Action Grafana & Prometheus docker stack
#
# ------------------------------------------------

name: GitHubAction-Grafana

on:
 push:
   branches: 
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone my repo
      - uses: actions/checkout@v3
      
      - name: List current folder
        run: ls -la
