# ------------------------------------------------
#
# GitHUb Action Grafana & Prometheus docker stack
#
# ------------------------------------------------

name: My-GitHubAction-Grafana

on:
 push:
   branches:
   - main

jobs:
  my_build:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone my repo
      - uses: actions/checkout@v3
      
      - name: List current folder
      - run: ls -la
